spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.50.12:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  application:
    name: order
  rabbitmq:
    host: 192.168.50.2
    port: 5672
    username: guest
    password: guest  
  redis:
    host: 192.168.50.2
    port: 6379    

# F 版本是默认不开启的， 需要手动开启。  
feign:
  hystrix:
    enabled: true
env:
  test2
girl:
  name: evan
  age: 18
