spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.50.12/springcloud_sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
  redis:
    host: 192.168.50.2
    port: 6379    

# F 版本是默认不开启的， 需要手动开启。  
feign:
  hystrix:
    enabled: true
